name: action1
on: [push]
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Get Code
      used: actions/checkout
    - name: Install deps
      run: npm install
    - name: Test code
      run: npm test
    - name: Deploy
      run: echo Deploying code

    
