name: issues
on: issues
jobs:
  DescribeIssue:
    runs-on: ubuntu-latest
    steps:
      - name: Display description
        run: echo 'Issue description ${{github.event.issue.title}} - ${{github.event.issue.body}}'
