name: action1
on: [push]
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout
      - name: Install deps
        run: npm install
      - name: Test code
        run: npm test
      - name: Deploy
        run: echo Deploying code

    
