name: action1
on: [push]
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install deps
        run: npm install
      - name: Lint code
        run: npm run lint
      - name: Build code
        run: npm run build
      - name: Test code
        run: npm test
      - name: Deploy
        run: echo Deploying code

    
